version: '3.8'
services:
  scylla:
    image: scylladb/scylla:latest
    container_name: aquasense-scylla
    ports:
      - "9042:9042"
    command: --smp 1 --memory 1G --overprovisioned 1 --api-address 0.0.0.0
    