name: aquasensecr

services:
  scylla:
    image: scylladb/scylla:2026.1.14

    ports:
      - "127.0.0.1:9042:9042"

    volumes:
      - scylla_data:/var/lib/scylla

    command:
      - --developer-mode
      - "1"
      - --smp
      - "1"
      - --memory
      - "2G"
      - --overprovisioned
      - "1"

volumes:
  scylla_data:
